### PR TITLE
Cleanup and fix windows handle leak

### LINKED ISSUE #14: Unclear ownership semantics cause leaks
Let's say you are on Windows and use the `TryFrom<Pid>` to get a `ProcessHandle`. This internally opens the process handle associated with that `Pid`. However there's no `Drop` implementation, so this handle gets leaked. Similar leaks might happen on other platforms.

### PR DESCRIPTION
**Pull request by P1n3appl3**
To fix #14 we have to add a `Drop` impl for the windows `ProcessHandle`. This also means that we need to remove the `Copy` and `Clone` impls for that struct to avoid closing the handle while a copy is still held.

It seems unfortunate to have all the other platforms impl copy/clone for the handle and for windows to have neither. I think the best middle ground would be to remove `Copy` across the board, and then make the windows `ProcessHandle` use an `Arc` internally so it can still impl `Clone`, but if we're fine with the asymmetry between platforms we can leave it as is.

I also took the liberty of updating the edition from 2015 to 2021, running rustfmt, and updating the dependencies. `winapi` has subsumed the old `kernel32` crate, so I removed the latter. If these cleanup changes aren't wanted I can revert them and just include the bug fix.

Fixes #14

### CODE REVIEW

File: tests/readme_test.rs [hunk 1]
```diff
@@ -1,6 +0,0 @@
-extern crate docmatic;
-
-#[test]
-fn test_readme() {
```
Comment (acj) [inline tests/readme_test.rs:4]: Why was this removed?

**Review by acj — COMMENTED** [review]
Thanks for working on this!

A few initial thoughts:

> remove Copy across the board, and then make the windows ProcessHandle use an Arc internally so it can still impl Clone

I like that suggestion. Having `ProcessHandle` be `Copy` assumes that it'll always be something like a unix PID with no associated resources, which isn't always true. The minor API breakage should be easy enough for downstream projects to handle. (Will test this before we merge.)

> I also took the liberty of updating the edition from 2015 to 2021, running rustfmt, and updating the dependencies. winapi has subsumed the old kernel32 crate, so I removed the latter. If these cleanup changes aren't wanted I can revert them and just include the bug fix.

The cleanups are good and appreciated. Would you mind splitting the upgrade/cleanup changes into a separate commit from the fix, please? The diff is a bit noisy with everything combined.

File: tests/readme_test.rs (hunk 1 above)
Comment (P1n3appl3) [reply tests/readme_test.rs:4]: Oh sorry, it was failing locally and I assumed the crate was unmaintained and obviated by `#![doc = include_str!("../README.md")]`. If you want I can put it back, but I've added the doc include so it still gets tested as a doctest.

**Comment by acj** [comment]
Sorry for the CI issues. If you rebase your branch, I think the tests will pass.

**Comment by acj** [comment]
LGTM. I should have time in the next few days to test these changes in a couple of projects, and then we can merge.

**Comment by luser** [comment]
Oops. thanks for fixing this! For future reference: I generally appreciate when folks take the time to modernize/format my under-maintained crates. Thanks for splitting that into a separate commit, it makes reviewing the changes a lot easier!

Conceptually, I suppose we could use [`DuplicateHandle`](https://docs.microsoft.com/en-us/windows/win32/api/handleapi/nf-handleapi-duplicatehandle) for `Clone`, but maybe that's not worthwhile? [There's FFI for it hidden inside `std`](https://github.com/rust-lang/rust/blob/3b263ceb5cb89b6d53b5a03b47ec447c3a7f7765/library/std/src/sys/windows/handle.rs#L265) but it's not publicly accessible.

Longer-term, it looks like [the IO safety RFC](http://rust-lang.github.io/rfcs/3128-io-safety.html) has an [`OwnedHandle`](https://doc.rust-lang.org/std/os/windows/io/struct.OwnedHandle.html) type that would be suitable for use here when it stabilizes. It doesn't seem to implement `Clone`, though.

> It seems unfortunate to have all the other platforms impl copy/clone for the handle and for windows to have neither. I think the best middle ground would be to remove `Copy` across the board, and then make the windows `ProcessHandle` use an `Arc` internally so it can still impl `Clone`, but if we're fine with the asymmetry between platforms we can leave it as is.

Using an `Arc` seems like the least-effort way to enable this, I agree. Having these handles be `Copy` was probably a mistake in the original design, honestly. The macOS code likely needs this same fix!

The Linux code could even be made more robust by using a `pidfd` instead of a raw `pid_t`. Looks like [here's some work afoot](https://github.com/rust-lang/rust/issues/82971) to add support for getting a `pidfd` while spawning a `Child` process in `std`, which would be nice.

**Comment by acj** [comment]
I tested this with a couple of downstream projects. At least one crate (remoteprocess) references the `RawHandle`, which is currently public, and passes the underlying handle to other Windows API functions. That's convenient, but I wonder if that usage of the underlying handle should be discouraged since this crate is focused on reading memory.

A few ideas:
1. Keep the inner type and its handle private, as they are in this PR. remoteprocess could hold a `ProcessHandle` for reading memory and define its own handle-wrapping type to use with other parts of the Windows API
2. Implement `Deref` on `ProcessHandle` so that downstream crates can get access to the underlying handle without knowing `ProcessHandle`'s implementation
3. Make the inner type and its handle public, roughly matching the current implementation

@benfred wdyt?

**Comment by luser** [comment]
> I tested this with a couple of downstream projects. At least one crate (remoteprocess) references the `RawHandle`, which is currently public, and passes the underlying handle to other Windows API functions. That's convenient, but I wonder if that usage of the underlying handle should be discouraged since this crate is focused on reading memory.

I can understand the motivation, since we do provide APIs for getting a process handle from a `Child` process. Perhaps those bits could be pulled out into a standalone crate, and this crate's API could just accept `T: AsRawHandle` and similar? I'm not sure if `std` has a useful cross-platform type for this currently. The "get a process handle" and "use a process handle to read memory" functionality are complementary but don't *need* to be tied together.

I have some other utility crates like [`spawn-task-port`](https://github.com/luser/spawn-task-port)–for getting a Mach task port as part of spawning a child process, removing the need to use the locked-down `task_for_pid` API, and [`spawn-ptrace`](https://github.com/luser/spawn-ptrace) which handles spawning a child process with `ptrace` enabled prior to `exec`. These would be more useful if they had some common types or traits to work with, making interop easier.

**Comment by acj** [comment]
> I can understand the motivation, since we do provide APIs for getting a process handle from a Child process. Perhaps those bits could be pulled out into a standalone crate, and this crate's API could just accept T: AsRawHandle and similar?

That sounds reasonable to me.

We'd still need a solution for remoteprocess's use of the inner handle. I'm leaning towards option 2 in my last post (implement `Deref`) since, if my read of the docs is correct, it's meant for scenarios like this where you're building smart pointers. If there's no objection, I'll put up a PR for that piece, and then I think we'll be unblocked to merge this PR. Then we can sketch out what a separate crate for process handles might look like?

**Comment by acj** [comment]
@P1n3appl3 Thanks for the fix! It's in 0.1.4.
